# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161019_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='operator',
            field=models.CharField(choices=[('+', '+'), ('-', '-'), ('*', '*'), ('/', '/')], max_length=1),
        ),
    ]
