# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161019_1913'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Operator',
            new_name='Operation',
        ),
    ]
