# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161019_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
