# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_operation_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='operation',
            name='operator',
            field=models.CharField(choices=[('+', 'Add'), ('-', 'Subtract'), ('*', 'Multiply'), ('/', 'Divide')], max_length=1),
        ),
    ]
