# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20161019_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_level',
            field=models.CharField(choices=[('o', 'Owner'), ('a', 'Account_User')], max_length=1),
        ),
    ]
