# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20161020_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_level',
            field=models.CharField(blank=True, choices=[('o', 'Owner'), ('a', 'Account_User')], default='a', max_length=1, null=True),
        ),
    ]
